### ISSUE TITLE
Change license to GPLv2 or any other copyleft

### ISSUE THREAD

**Issue by stokito** [iguana-project/iguana#1]
> Iguana is an open source issue

But it's license CC BY-SA 4.0 is [not approved by OCI](https://opensource.org/licenses/) to use for source code.
Generally the CC licenses aren't supposed to be used for source code.

https://opensource.stackexchange.com/questions/10613/what-is-the-main-difference-between-gpl-and-cc 

Probably the most similar license would be GPLv2 (not v3 whish is more restrictive). I'ts used by Linux and Git.
Please change the license or use dual licensing.

See related https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3753#issuecomment-1523014745

**Comment by caucaMe** [comment]
We are very much aware of the fact that creative commons licenses are not suitable for source code and have the plan to change it with a stable 1.0 version - see https://iguana-project.github.io/#plans. However since the progress over the last years has been fairly stale we want to change the license rather sooner than later.
Currently we try to reach previous contributors to ask for their opinion on whether they prefer a more permissive license or one with a copyleft-effect. We expect to be able to make a choice within the next month.

Thank you for bringing this up once again. In case you need a faster solution feel free to contact us as well.

**Comment by caucaMe** [comment]
As of today we changed the license from CC-BY-SA 4.0 to BSD-2-Clause.

**Comment by stokito** [comment]
Thank you
