### ISSUE TITLE
Missing nginx default file

### ISSUE THREAD

**Issue by NanoSymmetry** [iguana-project/iguana#3]
The `nginx.conf` file is missing leading to built docker containers to fail to run.

Command: `docker run -it -p 80:8000 -v ~/projects/iguana/files:/files <Iguana image ID>`
Output:
```shell
Creating default files on the volume.
Traceback (most recent call last):
  File "/usr/local/bin/docker_entrypoint.py", line 57, in <module>
    copy_file(src_path, path.join(FILES_DIR, df))
  File "/usr/local/lib/python3.8/distutils/file_util.py", line 104, in copy_file
    raise DistutilsFileError(
distutils.errors.DistutilsFileError: can't copy '/iguana/files_default/nginx.conf': doesn't exist or not a regular file
```

**Comment by mammo0** [comment]
Hello,

did you build the Docker image by yourself?
-> Then please provide the build command that you used.

 Or did you use an existing image?
-> Please provide the used image tag.

**Comment by NanoSymmetry** [comment]
I used my own image using the following command: `docker build -f Dockerfile . --build-arg USE_NGINX=true --build-arg VARIANT=development`

Taking a peek at the entry point file it appears to be looking in the `/files` for the config file however the only place I see a nginx config is within the docker directory as `nginx_template.conf`

**Comment by mammo0** [comment]
Ok, I know where the problem is:
The current implementation of the `Dockerfile` does not intend that a `development` image contains a nginx server. Please have a look at the following snippet:
https://github.com/iguana-project/iguana/blob/f313ca4557456898d59c52dd60b9f09a86a1c742/Dockerfile#L94-L107

Here you can see, that the `nginx.conf` file is only created if the `VARIANT` variable **is not** `development`.

Unfortunately this behavior is not documented anywhere. ~Maybe I find some time this weekend to implement a quick check in the `Dockerfile` to prevent using `--build-arg USE_NGINX=true` and `--build-arg VARIANT=development` together.~

**But please keep also in mind that this project didn't get much attention in the last years. As an example it still uses Django version 2.2 which is EOL since April 2022!**
Please don't expect any major changes in the future to the code of this project. In my opinion to bring this project back to life not only the dependencies have to be updated, but also a lot of code refactoring has to be done.

**Comment by mammo0** [comment]
With commit 5e21064 I changed the `Dockerfile` to validate the build arguments. Now an error is thrown if `USE_NGINX=true` and `VARIANT=development` are both set.

**Comment by NanoSymmetry** [comment]
I see, I'd love to help out as this project looks like exactly what I'm looking for. Unfortunately, I'm not confident with my programming skills.
I appreciate your help and insight for the project!

**Comment by NanoSymmetry** [comment]
> With commit [5e21064](https://github.com/iguana-project/iguana/commit/5e21064f760e97123154fece85632ed6a2d638a6) I changed the `Dockerfile` to validate the build arguments. Now an error is thrown if `USE_NGINX=true` and `VARIANT=development` are both set.

This commit fixed the error set out in the issue.

**Comment by mammo0** [comment]
> I see, I'd love to help out as this project looks like exactly what I'm looking for.

Thank you for liking our project. I appreciate that :)

Just an additional note: The project itself was part of a course during a semester at my university back in 2016/2017. At the end mostly all desired features were implemented and the application is still working today.
But as I stated out before, such a project needs continuous maintenance. And for an open source project this is not easy to ensure.

Therefore, if you use this application, I would suggest that - in it current stage with a lot of outdated dependencies - it should be not reachable from the internet. Just to be safe ;)
